### ISSUE TITLE
Merge Qrochet into Tenet?

### ISSUE THREAD

**Issue by mofeing** [bsc-quantic/Qrochet.jl#44]
`Qrochet` has been a place where to experiment with Quantum Tensor Networks outside of `Tenet`, so we could break things fast without compromising other code depending on `Tenet`.
We now have a clearer view of what interface should we provide. Also, as the number of serious users grows, we require a more stable library.

Thus I'm proposing to **move the code back to `Tenet`**. The benefits that I believe we would get are:
- New users might get confused with 2 packages for TNs, and currently all of our work is based on top of Qrochet.
- Qrochet doesn't add any strong dependency over Tenet, so it wouldn't mean to have a heavier package in the end.
- Better exploit structural and behavioral inheritance in the Tensor Network type hierarchy.
- `Qrochet` is not a great name.

Since there are no overheads or costs involved, I don't think there are any cons.

My idea is that once that we merge back Qrochet into Tenet, which will be a progressive process, we should be close to releasing Tenet 1.0.

**Comment by Todorbsc** [comment]
In my opinion, it could be a nice idea to have all kinds of tensor networks (in this case `Qrochet`) inside `Tenet` because, after all, they are still tensor networks and because of the list of reasons you wrote above. 

The discussion would be about how we plan to merge it back in `Tenet`, e.g. as an extension of `Tenet`.

Also, I think it's fine to release a stable version of `Tenet` (1.0) after doing this, as well as solving the important bugs there may exist for the basic functioning of `Tenet`.
